---
/pid_controller:
  ros__parameters:
    # vector indices correspond to x,y,z position,
    # then roll,pitch,yaw orientation gains
    kp: [100.0, 100.0, 200.0, -20.0, 40.0, 150.0]
    ki: [0.0, 0.0, 4.0, 0.0, 0.0, 0.0]
    kd: [1.0, 0.0, 8.0, 0.0, 0.0, 0.0]
    imax: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    imin: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    antiwindup: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
