---
/pid_controller:
  ros__parameters:
    # vector indices correspond to x,y,z position,
    # then roll,pitch,yaw orientation gains
    kp: [60.0, 50.0, 71.0, -140.0, 50.0, 200.0]
    ki: [0.0, 0.0, 2.7, 0.0, 0.0, 0.0]
    kd: [64.0, 0.35, 22.5, -14.5, 3.0, 10.0]
    imax: [0.0, 0.0, 1.7, 0.0, 0.0, 2.0]
    imin: [0.0, 0.0, -1.7, 0.0, 0.0, -2.0]
    antiwindup: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
