# ROS-Gazebo bridge configuration
# Add topic bridges in this list, like:
# - topic_name: "/example_topic"
#   ros_type: "std_msgs/String"
#   gz_type: "gz.msgs.StringMsg"

# IMU configuration.
- ros_topic_name: "/imu/data_raw/imu"
  gz_topic_name: "/imu/data_raw/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "/imu/data_raw/imu_mag"
  gz_topic_name: "/imu/data_raw/imu_mag"
  ros_type_name: "sensor_msgs/msg/MagneticField"
  gz_type_name: "gz.msgs.Magnetometer"
  direction: GZ_TO_ROS
