[workspace]
channels = ["conda-forge", "https://prefix.dev/robostack-jazzy"]
name = "mil2"
version = "0.1.0"

[[workspace.platforms]]
platform = "linux-64"
glibc = "2.34"

[[workspace.platforms]]
platform = "linux-aarch64"
glibc = "2.34"

[tasks]

[dependencies]
ccache = ">=4.14,<5"
colcon-common-extensions = ">=0.3.0,<0.4"
gxx = ">=16.2.0,<16.3"
make = ">=4.4.1,<5"

ros2-ros-core = ">=0.11.0,<0.12"
ros2-rmw-zenoh-cpp = ">=0.2.10,<0.3"
ros2-geometry2 = ">=0.36.22,<0.37"

[environments.sub-jetson.dependencies]
# binutils = ">=2.46.1,<3"
eigen = ">=5.0.1,<6"
nlohmann_json = ">=3.12.0,<4"
ros2-backward-ros = ">=1.0.8,<2"
ros2-robot-localization = ">=3.8.3,<4"
ros2-behaviortree-cpp = ">=4.9.1,<5"
ros2-vision-opencv = ">=4.1.0,<5"
ros2-ros-gz = ">=1.0.23,<2"
ros2-control-toolbox = ">=4.11.1,<5"
pre-commit = ">=4.6.2,<5"

[environments.prop-jetson.dependencies]
ros2-ros-gz = ">=1.0.23,<2"
ros2-control-toolbox = ">=4.11.1,<5"
ros2-nav-msgs = ">=5.3.8,<6"
ros2-velodyne-driver = ">=2.5.1,<3"
ros2-velodyne-pointcloud = ">=2.5.1,<3"
ros2-robot-localization = ">=3.8.3,<4"
ros2-imu-filter-madgwick = ">=2.1.5,<3"
ros2-pcl-ros = ">=2.6.5,<3"

[activation.env]
LIBRARY_PATH = "$CONDA_PREFIX/lib"
LD_LIBRARY_PATH = "$CONDA_PREFIX/lib:$LD_LIBRARY_PATH"
