# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: robotx/rx_common.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 33, 5, "", "robotx/rx_common.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n\x16robotx/rx_common.proto\x12\x15robocommand.robotx.v1*\x99\x01\n\x06RxTask\x12\x10\n\x0cTASK_UNKNOWN\x10\x00\x12\r\n\tTASK_NONE\x10\x01\x12\x15\n\x11TASK_SAFE_PASSAGE\x10\x02\x12\x1c\n\x18TASK_INFRA_SURVEY_REPAIR\x10\x03\x12\x1e\n\x1aTASK_COORDINATED_LOGISTICS\x10\x04\x12\x19\n\x15TASK_DYNAMIC_INCIDENT\x10\x05*I\n\x0bVehicleType\x12\x10\n\x0cTYPE_UNKNOWN\x10\x00\x12\x0c\n\x08TYPE_USV\x10\x01\x12\x0c\n\x08TYPE_UUV\x10\x02\x12\x0c\n\x08TYPE_UAV\x10\x03*\xbb\x01\n\x0b\x42\x65\x61\x63onState\x12\x18\n\x14\x42\x45\x41\x43ON_STATE_UNKNOWN\x10\x00\x12\x14\n\x10\x42\x45\x41\x43ON_STATE_OFF\x10\x01\x12\x1d\n\x19\x42\x45\x41\x43ON_STATE_FLASHING_RED\x10\x02\x12\x1f\n\x1b\x42\x45\x41\x43ON_STATE_FLASHING_GREEN\x10\x03\x12\x1e\n\x1a\x42\x45\x41\x43ON_STATE_FLASHING_BLUE\x10\x04\x12\x1c\n\x18\x42\x45\x41\x43ON_STATE_STEADY_BLUE\x10\x05*p\n\x15PipelineSegmentStatus\x12\x1c\n\x18PIPELINE_SEGMENT_UNKNOWN\x10\x00\x12\x1b\n\x17PIPELINE_SEGMENT_INTACT\x10\x01\x12\x1c\n\x18PIPELINE_SEGMENT_DAMAGED\x10\x02*]\n\x0b\x46lightPhase\x12\x18\n\x14\x46LIGHT_PHASE_UNKNOWN\x10\x00\x12\x19\n\x15\x46LIGHT_PHASE_GROUNDED\x10\x01\x12\x19\n\x15\x46LIGHT_PHASE_AIRBORNE\x10\x02*Y\n\x05\x43olor\x12\x11\n\rCOLOR_UNKNOWN\x10\x00\x12\r\n\tCOLOR_RED\x10\x01\x12\x0f\n\x0b\x43OLOR_GREEN\x10\x02\x12\x0e\n\nCOLOR_BLUE\x10\x03\x12\r\n\tCOLOR_ANY\x10\x04\x62\x08\x65\x64itionsp\xe9\x07"
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "robotx.rx_common_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_RXTASK"]._serialized_start = 50
    _globals["_RXTASK"]._serialized_end = 203
    _globals["_VEHICLETYPE"]._serialized_start = 205
    _globals["_VEHICLETYPE"]._serialized_end = 278
    _globals["_BEACONSTATE"]._serialized_start = 281
    _globals["_BEACONSTATE"]._serialized_end = 468
    _globals["_PIPELINESEGMENTSTATUS"]._serialized_start = 470
    _globals["_PIPELINESEGMENTSTATUS"]._serialized_end = 582
    _globals["_FLIGHTPHASE"]._serialized_start = 584
    _globals["_FLIGHTPHASE"]._serialized_end = 677
    _globals["_COLOR"]._serialized_start = 679
    _globals["_COLOR"]._serialized_end = 768
# @@protoc_insertion_point(module_scope)
