# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: robotx/rx_commands.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 33, 5, "", "robotx/rx_commands.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import ocs.proto.common_pb2 as common__pb2
from ocs.proto.robotx import rx_common_pb2 as robotx_dot_rx__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x18robotx/rx_commands.proto\x12\x15robocommand.robotx.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0c\x63ommon.proto\x1a\x16robotx/rx_common.proto"\xf2\x03\n\tRxCommand\x12\x0f\n\x07team_id\x18\x01 \x01(\t\x12\x0b\n\x03seq\x18\x02 \x01(\r\x12+\n\x07sent_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nvehicle_id\x18\x04 \x01(\t\x12\x34\n\trun_start\x18\n \x01(\x0b\x32\x1f.robocommand.robotx.v1.RunStartH\x00\x12\x46\n\x12\x61ssistance_request\x18\x0b \x01(\x0b\x32(.robocommand.robotx.v1.AssistanceRequestH\x00\x12;\n\rkeep_out_zone\x18\x0c \x01(\x0b\x32".robocommand.robotx.v1.KeepOutZoneH\x00\x12\x34\n\tall_clear\x18\r \x01(\x0b\x32\x1f.robocommand.robotx.v1.AllClearH\x00\x12G\n\x13moving_object_alert\x18\x0e \x01(\x0b\x32(.robocommand.robotx.v1.MovingObjectAlertH\x00\x12\x44\n\x11readiness_confirm\x18\x0f \x01(\x0b\x32\'.robocommand.robotx.v1.ReadinessConfirmH\x00\x42\x06\n\x04\x62ody"3\n\x08RunStart\x12\x17\n\x0f\x64\x65\x63laration_seq\x18\x01 \x01(\r\x12\x0e\n\x06run_id\x18\x02 \x01(\r"~\n\x11\x41ssistanceRequest\x12/\n\x08position\x18\x01 \x01(\x0b\x32\x1d.robocommand.common.v1.LatLng\x12\x38\n\x0cvehicle_type\x18\x02 \x01(\x0e\x32".robocommand.robotx.v1.VehicleType":\n\x10ReadinessConfirm\x12\x12\n\nreport_seq\x18\x01 \x01(\r\x12\x12\n\nvehicle_id\x18\x02 \x01(\t"\x88\x01\n\x0bKeepOutZone\x12-\n\x06\x63\x65nter\x18\x01 \x01(\x0b\x32\x1d.robocommand.common.v1.LatLng\x12\x10\n\x08radius_m\x18\x02 \x01(\x02\x12\x38\n\x0cvehicle_type\x18\x03 \x01(\x0e\x32".robocommand.robotx.v1.VehicleType"D\n\x08\x41llClear\x12\x38\n\x0cvehicle_type\x18\x01 \x01(\x0e\x32".robocommand.robotx.v1.VehicleType"\xb0\x01\n\x11MovingObjectAlert\x12/\n\x08position\x18\x01 \x01(\x0b\x32\x1d.robocommand.common.v1.LatLng\x12\x13\n\x0bheading_deg\x18\x02 \x01(\x02\x12\x11\n\tspeed_mps\x18\x03 \x01(\x02\x12\x42\n\x16\x61\x66\x66\x65\x63ted_vehicle_types\x18\x04 \x03(\x0e\x32".robocommand.robotx.v1.VehicleTypeb\x08\x65\x64itionsp\xe9\x07'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "robotx.rx_commands_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_RXCOMMAND"]._serialized_start = 123
    _globals["_RXCOMMAND"]._serialized_end = 621
    _globals["_RUNSTART"]._serialized_start = 623
    _globals["_RUNSTART"]._serialized_end = 674
    _globals["_ASSISTANCEREQUEST"]._serialized_start = 676
    _globals["_ASSISTANCEREQUEST"]._serialized_end = 802
    _globals["_READINESSCONFIRM"]._serialized_start = 804
    _globals["_READINESSCONFIRM"]._serialized_end = 862
    _globals["_KEEPOUTZONE"]._serialized_start = 865
    _globals["_KEEPOUTZONE"]._serialized_end = 1001
    _globals["_ALLCLEAR"]._serialized_start = 1003
    _globals["_ALLCLEAR"]._serialized_end = 1071
    _globals["_MOVINGOBJECTALERT"]._serialized_start = 1074
    _globals["_MOVINGOBJECTALERT"]._serialized_end = 1250
# @@protoc_insertion_point(module_scope)
