# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: robotx/rx_requests.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 33, 5, "", "robotx/rx_requests.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import ocs.proto.common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x18robotx/rx_requests.proto\x12\x15robocommand.robotx.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0c\x63ommon.proto"\xa0\x01\n\tRxRequest\x12\x0f\n\x07team_id\x18\x01 \x01(\t\x12\x0b\n\x03seq\x18\x02 \x01(\r\x12+\n\x07sent_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12@\n\x0frun_declaration\x18\n \x01(\x0b\x32%.robocommand.robotx.v1.RunDeclarationH\x00\x42\x06\n\x04\x62ody"\xae\x02\n\x0eRunDeclaration\x12\x13\n\x0bvehicle_ids\x18\x01 \x03(\t\x12\x33\n\ntask1_tier\x18\x02 \x01(\x0e\x32\x1f.robocommand.common.v1.TaskTier\x12\x33\n\ntask2_tier\x18\x03 \x01(\x0e\x32\x1f.robocommand.common.v1.TaskTier\x12\x33\n\ntask3_tier\x18\x04 \x01(\x0e\x32\x1f.robocommand.common.v1.TaskTier\x12\x33\n\ntask4_tier\x18\x05 \x01(\x0e\x32\x1f.robocommand.common.v1.TaskTier\x12\x33\n\x0cuav_geofence\x18\x06 \x03(\x0b\x32\x1d.robocommand.common.v1.LatLngb\x08\x65\x64itionsp\xe9\x07'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "robotx.rx_requests_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_RXREQUEST"]._serialized_start = 99
    _globals["_RXREQUEST"]._serialized_end = 259
    _globals["_RUNDECLARATION"]._serialized_start = 262
    _globals["_RUNDECLARATION"]._serialized_end = 564
# @@protoc_insertion_point(module_scope)
