---
# ##########################################################################
# ###  !!!CHANGE LATER                   ###


velodyne_transform_node:
  ros__parameters:
    model: VLP16
    calibration: "/opt/ros/jazzy/share/velodyne_pointcloud/params/VLP16db.yaml"
    frame_id: "velodyne"
    min_range: 0.4
    max_range: 130.0
    view_direction: 0.0
    view_width: 6.28
    organize_cloud: false
