---
/subjugator_localization:
  ros__parameters:
    world_frame: odom
    odom_frame: odom
    base_link_frame: base_link

    odom0: "/dvl/odom"
    odom0_config:
      [
        true, true, true,
        true, true, true,
        true, true, true,
        false, false, false,
        false, false, false,
      ]
    odom0_differential: true
    odom0_relative: false
    odom0_queue_size: 10
    
    print_diagnostics: true
    publish_acceleration: true
    debug: true
    debug_out_file: "/home/sub9/debug.txt"
    frequency: 7.0
    disabled_at_startup: true
