# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: acoustic_pinger_config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1c\x61\x63oustic_pinger_config.proto\x12\x12mil_acoustic_modem")\n\x14\x41\x63ousticPingerConfig\x12\x11\n\tfrequency\x18\x01 \x01(\rb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "acoustic_pinger_config_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _ACOUSTICPINGERCONFIG._serialized_start = 52
    _ACOUSTICPINGERCONFIG._serialized_end = 93
# @@protoc_insertion_point(module_scope)
