# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: heartbeat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0fheartbeat.proto\x12\x12mil_acoustic_modem"\xaa\x01\n\tHeartbeat\x12\r\n\x05state\x18\x01 \x01(\t\x12\x12\n\nposition_x\x18\x02 \x01(\x02\x12\x12\n\nposition_y\x18\x03 \x01(\x02\x12\r\n\x05speed\x18\x04 \x01(\x02\x12\x0f\n\x07heading\x18\x05 \x01(\x02\x12\x0c\n\x04roll\x18\x06 \x01(\x02\x12\r\n\x05pitch\x18\x07 \x01(\x02\x12\r\n\x05\x64\x65pth\x18\x08 \x01(\x02\x12\x0c\n\x04task\x18\t \x01(\t\x12\x0c\n\x04type\x18\n \x01(\tb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "heartbeat_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _HEARTBEAT._serialized_start = 40
    _HEARTBEAT._serialized_end = 210
# @@protoc_insertion_point(module_scope)
