# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mil_message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pipeline_survey_report_pb2 as pipeline__survey__report__pb2
import heartbeat_pb2 as heartbeat__pb2
import acoustic_pinger_config_pb2 as acoustic__pinger__config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n\x11mil_message.proto\x12\x12mil_acoustic_modem\x1a\x1cpipeline_survey_report.proto\x1a\x0fheartbeat.proto\x1a\x1c\x61\x63oustic_pinger_config.proto\"\x92\x02\n\nMilMessage\x12\x30\n\x04type\x18\x01 \x01(\x0e\x32\".mil_acoustic_modem.MilMessageType\x12\x32\n\theartbeat\x18\x02 \x01(\x0b\x32\x1d.mil_acoustic_modem.HeartbeatH\x00\x12J\n\x16pipeline_survey_report\x18\x03 \x01(\x0b\x32(.mil_acoustic_modem.PipelineSurveyReportH\x00\x12J\n\x16\x61\x63oustic_pinger_config\x18\x04 \x01(\x0b\x32(.mil_acoustic_modem.AcousticPingerConfigH\x00\x42\x06\n\x04\x62ody*\x8a\x01\n\x0eMilMessageType\x12\x1e\n\x1aMIL_MESSAGE_TYPE_HEARTBEAT\x10\x00\x12+\n'MIL_MESSAGE_TYPE_PIPELINE_SURVEY_REPORT\x10\x01\x12+\n'MIL_MESSAGE_TYPE_ACOUSTIC_PINGER_CONFIG\x10\x02\x62\x06proto3"
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "mil_message_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _MILMESSAGETYPE._serialized_start = 396
    _MILMESSAGETYPE._serialized_end = 534
    _MILMESSAGE._serialized_start = 119
    _MILMESSAGE._serialized_end = 393
# @@protoc_insertion_point(module_scope)
