# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pipeline_survey_report.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1cpipeline_survey_report.proto\x12\x12mil_acoustic_modem"\x9a\x02\n\x14PipelineSurveyReport\x12\x1e\n\x16\x61\x63tive_buoy_position_x\x18\x01 \x01(\x02\x12\x1e\n\x16\x61\x63tive_buoy_position_y\x18\x02 \x01(\x02\x12P\n\x08segments\x18\x03 \x03(\x0e\x32>.mil_acoustic_modem.PipelineSurveyReport.PipelineSegmentStatus"p\n\x15PipelineSegmentStatus\x12\x1c\n\x18PIPELINE_SEGMENT_UNKNOWN\x10\x00\x12\x1b\n\x17PIPELINE_SEGMENT_INTACT\x10\x01\x12\x1c\n\x18PIPELINE_SEGMENT_DAMAGED\x10\x02\x62\x06proto3',
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR,
    "pipeline_survey_report_pb2",
    globals(),
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _PIPELINESURVEYREPORT._serialized_start = 53
    _PIPELINESURVEYREPORT._serialized_end = 335
    _PIPELINESURVEYREPORT_PIPELINESEGMENTSTATUS._serialized_start = 223
    _PIPELINESURVEYREPORT_PIPELINESEGMENTSTATUS._serialized_end = 335
# @@protoc_insertion_point(module_scope)
