# Online bagger client calls this service to obtain a list of topics to be bagged
# The topics will be displayed on client ui

---
string[] topics # Contains all topic names to bag in the online bagger server.
