# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 33, 5, "", "common.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0c\x63ommon.proto\x12\x15robocommand.common.v1"-\n\x06LatLng\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01*S\n\nRobotState\x12\x11\n\rSTATE_UNKNOWN\x10\x00\x12\x10\n\x0cSTATE_KILLED\x10\x01\x12\x10\n\x0cSTATE_MANUAL\x10\x02\x12\x0e\n\nSTATE_AUTO\x10\x03*b\n\x08TaskTier\x12\x10\n\x0cTIER_UNKNOWN\x10\x00\x12\r\n\tTIER_NONE\x10\x01\x12\r\n\tTIER_CORE\x10\x02\x12\x11\n\rTIER_ADVANCED\x10\x03\x12\x13\n\x0fTIER_DISRUPTIVE\x10\x04\x62\x08\x65\x64itionsp\xe9\x07'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "common_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_ROBOTSTATE"]._serialized_start = 86
    _globals["_ROBOTSTATE"]._serialized_end = 169
    _globals["_TASKTIER"]._serialized_start = 171
    _globals["_TASKTIER"]._serialized_end = 269
    _globals["_LATLNG"]._serialized_start = 39
    _globals["_LATLNG"]._serialized_end = 84
# @@protoc_insertion_point(module_scope)
