robogym_project:
  name: "Demo Project"
  world_file: "src/default/world/file"
  model_name: "sub9"
  random_spawn_space:
    enabled: false
    coord1_4d: [0.0, 0.0, 0.0, 0.0]
    coord2_4d: [0.0, 0.0, 0.0, 0.0]
  input_topics:
    imu/processed:
      - orientation.x
      - orientation.y
      - angular_velocity.z
    dvl/processed:
      - velocity.x
      - velocity.y
  output_topics:
    trajectory/4_deg:
      - x
      - y
      - yaw
  tensor_spec:
    input_features:
      - imu/processed:orientation.x
      - imu/processed:orientation.y
      - imu/processed:angular_velocity.z
      - dvl/processed:velocity.x
      - dvl/processed:velocity.y
    output_features:
      - trajectory/4_deg:x
      - trajectory/4_deg:y
      - trajectory/4_deg:yaw
    input_dim: 5
    output_dim: 3
