---
robogym_project:
    name: "Demo Project"
    world_file: "src/default/world/file"
    model_name: "sub9"
    random_spawn_space:
        enabled: false
        coord1_4d: [0.0, 0.0, 0.0, 0.0]
        coord2_4d: [0.0, 0.0, 0.0, 0.0]
    input_topics:
        /ping:
            - frequency
            - origin_direction_body.x
            - origin_direction_body.y
            - origin_direction_body.z
            - origin_distance_m
    output_topics:
        /goal/trajectory:
            - orientation.w
            - orientation.x
            - orientation.y
            - orientation.z
            - position.x
            - position.y
            - position.z
    tensor_spec:
        input_features:
            - /ping:frequency
            - /ping:origin_direction_body.x
            - /ping:origin_direction_body.y
            - /ping:origin_direction_body.z
            - /ping:origin_distance_m
        output_features:
            - /goal/trajectory:orientation.w
            - /goal/trajectory:orientation.x
            - /goal/trajectory:orientation.y
            - /goal/trajectory:orientation.z
            - /goal/trajectory:position.x
            - /goal/trajectory:position.y
            - /goal/trajectory:position.z
        input_dim: 5
        output_dim: 7
