<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>subjugator_movement_manager</name>
  <version>0.0.0</version>
  <description>Resolves relative/absolute move commands into absolute goals for the path planner and reports arrival status.</description>
  <maintainer email="c.chavez@ufl.edu">Carlos Chavez</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>geometry_msgs</depend>
  <depend>mil_tools</depend>
  <depend>nav_msgs</depend>
  <depend>rclcpp</depend>
  <depend>subjugator_msgs</depend>

  <exec_depend>ros2launch</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
