---
name: Service healthcheck

# yamllint disable-line rule:truthy
on: push
  # schedule:
  #   # Run every day at midnight
  #   - cron: '0 0 * * *'

jobs:
  ufl:
    name: eduroam visibility healthcheck
    runs-on:
      group: mala-lab-noble
    steps:
      - name: zobelisk
        run: |
          ping -c 1 zobelisk.mil.ufl.edu &> /dev/null
      - name: workstation1
        run: |
          ping -c 1 workstation1.mil.ufl.edu &> /dev/null
      - name: workstation2
        run: |
          ping -c 1 workstation2.mil.ufl.edu &> /dev/null
      - name: workstation3
        run: |
          ping -c 1 workstation3.mil.ufl.edu &> /dev/null
